apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-test-app
  labels:
    app: automation-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automation-test
  template:
    metadata:
      labels:
        app: automation-test
    spec:
      containers:
        - name: nginx-server
          image: ghcr.io/svartastorken/automation-test:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
