apiVersion: v1
kind: Service
metadata:
  name: automation-test-service
spec:
  selector:
    app: automation-test
  ports:
    - name: http        
      port: 80          
      targetPort: 8080  
      protocol: TCP
